/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplomenu;

/**
 *
 * @author marcelo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menInternacionais = new javax.swing.JMenu();
        menNacionais = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menPecas = new javax.swing.JMenuItem();
        menAlimentos = new javax.swing.JMenuItem();
        menVestuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menTabelas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        menInternacionais.setText("Clientes");

        menNacionais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menNacionais.setText("Nacionais");
        menNacionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menNacionaisActionPerformed(evt);
            }
        });
        menInternacionais.add(menNacionais);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Internacionais");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menInternacionais.add(jMenuItem3);

        jMenuBar1.add(menInternacionais);

        jMenu2.setText("Fornecedores");

        menPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menPecas.setText("Peças");
        menPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPecasActionPerformed(evt);
            }
        });
        jMenu2.add(menPecas);

        menAlimentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menAlimentos.setText("Alimentos");
        menAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAlimentosActionPerformed(evt);
            }
        });
        jMenu2.add(menAlimentos);

        menVestuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menVestuario.setText("Vestuário");
        menVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menVestuarioActionPerformed(evt);
            }
        });
        jMenu2.add(menVestuario);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Exemplos");

        menTabelas.setText("Tabelas");
        menTabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menTabelasActionPerformed(evt);
            }
        });
        jMenu1.add(menTabelas);

        jMenuItem1.setText("For");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Desenhos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menNacionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menNacionaisActionPerformed
        // TODO add your handling code here:
        Nacionais n;
        n=new Nacionais();
        jDesktopPane1.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_menNacionaisActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         Internacionais n;
        n=new Internacionais();
        jDesktopPane1.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPecasActionPerformed
        // TODO add your handling code here:
        Pecas n;
        n=new Pecas();
        jDesktopPane1.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_menPecasActionPerformed

    private void menAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAlimentosActionPerformed
        // TODO add your handling code here:
        Alimentos n;
        n=new Alimentos();
        jDesktopPane1.add(n);
        n.setVisible(true);
        try {
            n.setMaximum(true);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_menAlimentosActionPerformed

    private void menVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menVestuarioActionPerformed
        // TODO add your handling code here:
        Vestuario n;
        n=new Vestuario();
        jDesktopPane1.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_menVestuarioActionPerformed

    private void menTabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menTabelasActionPerformed
        // TODO add your handling code here:
        Tabelas t;
        t =new Tabelas();
        jDesktopPane1.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_menTabelasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ComandoFor t;
        t =new ComandoFor();
        jDesktopPane1.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Desenhos t;
        t =new Desenhos();
        jDesktopPane1.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menAlimentos;
    private javax.swing.JMenu menInternacionais;
    private javax.swing.JMenuItem menNacionais;
    private javax.swing.JMenuItem menPecas;
    private javax.swing.JMenuItem menTabelas;
    private javax.swing.JMenuItem menVestuario;
    // End of variables declaration//GEN-END:variables
}
