/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplomenu;

import java.math.BigInteger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcelo
 */
public class Tabelas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tabelas
     */
    public Tabelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnMontarTabela = new javax.swing.JButton();
        btnTabuada = new javax.swing.JButton();
        txtTabuada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Tabelas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnMontarTabela.setText("Montar Tabela");
        btnMontarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontarTabelaActionPerformed(evt);
            }
        });

        btnTabuada.setText("Monta Tabuada");
        btnTabuada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabuadaActionPerformed(evt);
            }
        });

        txtTabuada.setText("6");

        jButton1.setText("Totas Tabuafdas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMontarTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTabuada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(txtTabuada, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnTabuada)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMontarTabela)
                            .addComponent(txtTabuada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMontarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontarTabelaActionPerformed
        // TODO add your handling code here:
        Object[] colunas;
        colunas = new Object[2];
        colunas[0]="Nome";
        colunas[1]="Idade";
        
        Object[][] linhas; 
        linhas = new Object[3][2];
        linhas[0][0]="Leonardo";
        linhas[0][1]="26";
        linhas[1][0]="Marcelo";
        linhas[1][1]="39";
        linhas[2][0]="Eliana";
        linhas[2][1]="29";
        
        DefaultTableModel tm;
        tm = new DefaultTableModel(linhas, colunas);
        
        
        jTable1.setModel(tm);
        
        
    }//GEN-LAST:event_btnMontarTabelaActionPerformed

    private void btnTabuadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabuadaActionPerformed
        // TODO add your handling code here:
        Object[] col;
        col=new Object[3];
        col[0]="Posição";
        col[1]="Tabuada";
        col[2]="Resultado";
        
        Object[][] lin;
        lin=new Object[10][3];
        BigInteger t,m;
        t=new BigInteger(txtTabuada.getText());
        for (int i = 0; i < 10; i++) {
            lin[i][0]=i+1;
            lin[i][1]="x"+t+"=";
            m=new BigInteger((i+1)+"");
            lin[i][2]=t.multiply(m);   
        }
        DefaultTableModel tm;
        tm =new DefaultTableModel(lin, col);
        jTable1.setModel(tm);
        
    }//GEN-LAST:event_btnTabuadaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Questão 6
        //Todas Tabuadas
        Object[] col;
        col=new Object[10];
        
        Object [][] lin;
        lin=new Object[10][10];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                lin[i][j]=(i+1)*(j+1);
            }
            col[i]="Tab "+(i+1);
        }
        DefaultTableModel tm;
        tm =new DefaultTableModel(lin, col);
        jTable1.setModel(tm);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMontarTabela;
    private javax.swing.JButton btnTabuada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTabuada;
    // End of variables declaration//GEN-END:variables
}
